[package]
name = "avr-delay"
version = "0.1.0"
edition = "2021"

[features]
fcpu-16mhz = []

[dependencies]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
lto = true
codegen-units = 1
panic = "abort"

